//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Logic.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy/Sell in National bank: .
        /// </summary>
        public static string BaySellNationalBank {
            get {
                return ResourceManager.GetString("BaySellNationalBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I cannot do this action, your current choosen date:.
        /// </summary>
        public static string CannotChangeDate {
            get {
                return ResourceManager.GetString("CannotChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change currency.
        /// </summary>
        public static string ChangeCurrencyButton {
            get {
                return ResourceManager.GetString("ChangeCurrencyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change date.
        /// </summary>
        public static string ChangeDateButton {
            get {
                return ResourceManager.GetString("ChangeDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose currency
        ///.
        /// </summary>
        public static string ChooseCurrency {
            get {
                return ResourceManager.GetString("ChooseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have choosen date.
        /// </summary>
        public static string ChoosenDate {
            get {
                return ResourceManager.GetString("ChoosenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency: .
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current choosen currency and date:
        ///.
        /// </summary>
        public static string CurrentCurrencyAndDate {
            get {
                return ResourceManager.GetString("CurrentCurrencyAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen date: .
        /// </summary>
        public static string DateNotchanged {
            get {
                return ResourceManager.GetString("DateNotchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day after.
        /// </summary>
        public static string DayAfterButton {
            get {
                return ResourceManager.GetString("DayAfterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day before.
        /// </summary>
        public static string DayBeforeButton {
            get {
                return ResourceManager.GetString("DayBeforeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date in this pattern: .
        /// </summary>
        public static string EnterDateByFormPattern {
            get {
                return ResourceManager.GetString("EnterDateByFormPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date in this pattern: .
        /// </summary>
        public static string EnterDateInPattern {
            get {
                return ResourceManager.GetString("EnterDateInPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot get future exchange currency. Please enter today`s date or past date.
        /// </summary>
        public static string EnteredFutureData {
            get {
                return ResourceManager.GetString("EnteredFutureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, invalid format of entered date. Try enter date in this format: .
        /// </summary>
        public static string InvalidFormatOfDate {
            get {
                return ResourceManager.GetString("InvalidFormatOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current selected currency and date.
        /// </summary>
        public static string ShowCurrencyAndDateButton {
            get {
                return ResourceManager.GetString("ShowCurrencyAndDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the exchange rate.
        /// </summary>
        public static string ShowExchangeRateButton {
            get {
                return ResourceManager.GetString("ShowExchangeRateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don`t know this currency.
        /// </summary>
        public static string UnknownCurrency {
            get {
                return ResourceManager.GetString("UnknownCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not known, how must i answer you.. :(.
        /// </summary>
        public static string UnknownMessageReceived {
            get {
                return ResourceManager.GetString("UnknownMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yestarday date.
        /// </summary>
        public static string YestardayDateButton {
            get {
                return ResourceManager.GetString("YestardayDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected:
        ///.
        /// </summary>
        public static string YouSelected {
            get {
                return ResourceManager.GetString("YouSelected", resourceCulture);
            }
        }
    }
}
